### ISSUE TITLE
Quest - Elwynn Forest : Fine Linen Goods

### ISSUE THREAD

**Issue by Icebeam666** [omghixd/Path-of-Classic-Bugtracker#4]
Quest/Spell/Item/Creature(ID) The ID is: 83
Quest/Spell/Item/Creature(ID) item=1019
The Current Behaviour is as following: Drop rate on Linen Scraps seems super low.

Expected Behaviour should be as following: Linen Scrap should have a higher drop chance.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by omghixd** [comment]
In the future i'd love if we could have some more information as to where this issue is. 

Nonetheless, Drop chance was pretty variated across all creatures it dropped from. But each should have been opped up with roughly 25% increasment on-top of their already existing drop chance.

//Fixes and closes this report.
