### ISSUE TITLE
[Item] {Jadefire Rogue} Recipe: Elixir of the Mongoose

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#480]
Quest/Spell/Item/Creature(ID) The ID is: 13491

The Current Behaviour is as following: Does not seem to drop the recipe / extremely low %.

Expected Behaviour should be as following: 4%ish droprate.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://classic.wowhead.com/item=13491/recipe-elixir-of-the-mongoose

**Comment by omghixd** [comment]
Creature ID 6201 now drops this item at 3.64% and ID 7106 drops this item at 4%

Thank you for reporting this.
//Fixed and Closing this report.

**Comment by Tyrvana** [comment]
Both me and Holyfather farmed these, at least +400 kills and still no drop.

**Comment by omghixd** [comment]
I apologize. We had to revert back to our old world. When i answered this report i was looking at the new implemented database of ours. And had double checked it there and simply forgot to check it on the old one.

- we moved back to the old one due to a crash related issue we have to solve on the new one. 

I've taken the time to ensure that the drop rates are as stated above in the old database as well. It should be good now!
