### ISSUE TITLE
Quest  [Breaking the Chain] 

### ISSUE THREAD

**Issue by Partycles** [omghixd/Path-of-Classic-Bugtracker#494]
![image](https://user-images.githubusercontent.com/75519680/101378641-b08be300-38f6-11eb-8941-74a3a530dcfb.png)
![image](https://user-images.githubusercontent.com/75519680/101378686-c00b2c00-38f6-11eb-9819-9b01a3b2371b.png)

Mob didn't appear tried killing other mob they respawn and the mob for the quest is still not there

**Comment by previlin** [comment]
Quest/Spell/Item/Creature(ID) The ID is: 
quest id=25167
The Current Behaviour is as following: 
Missing NPC  id=39251  https://www.wowhead.com/npc=39251/northwatch-supply-crate
and id=39245 https://www.wowhead.com/npc=39245/northwatch-lug
Expected Behaviour should be as following: 
https://www.youtube.com/watch?v=677VIxbSzXY
Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
https://www.wowhead.com/quest=25167/breaking-the-chain

**Comment by omghixd** [comment]
This area has been re-designed and will be available upon next liverealm restart.

Thank you for reporting this!
//Fixed and Closing this report.
